import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { Box, Heading } from "@chakra-ui/react";
import Slider from "@/Components/Home/Slider";
import HomeProducts from "@/Components/Home/HomeProducts";
import HomeProductsHeading from "@/Components/Home/HomeProductsHeading";
import AddProductsPage from "./AddProductPage";

const inter = Inter({ subsets: ["latin"] });

export default function Home({products}) {
  return (
    <>
      <Head>
        <title>ShopKart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        {/* <Slider />
        <HomeProductsHeading text={"Headphones For You"} />
        <HomeProducts products={products} /> */}
        <AddProductsPage />
      </Box>
    </>
  );
}

// Getting All The Data From API
export async function getStaticProps() {
  let res = await fetch("http://localhost:8080/products");
  let data = await res.json();

  return {
    props: {
      products: data,
    },
  };
}