import Head from "next/head";
import { Box, Heading } from "@chakra-ui/react";
import Slider from "@/Components/Home/Slider";
import HomeProducts from "@/Components/Home/HomeProducts";
import HomeProductsHeading from "@/Components/Home/HomeProductsHeading";

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>ShopKart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Slider />
        <HomeProductsHeading text={"Headphones For You"} />
        <HomeProducts products={products} />
      </Box>
    </>
  );
}

export async function getStaticProps() {
  let res = await fetch("http://localhost:8080/products");
  let data = await res.json();

  return {
    props: {
      products: data,
    },
  };
}
