import Head from "next/head";
import { Box, Heading, Image } from "@chakra-ui/react";
import Slider from "@/Components/Home/Slider";
import HomeProducts from "@/Components/Home/HomeProducts";
import HomeProductsHeading from "@/Components/Home/HomeProductsHeading";
import HomeProductSlider from "@/Components/Home/HomProductsSlider/HomeProductSlider";
import Discover from "@/Components/Home/Discover";
import DareToLeap from "@/Components/Home/DareToLeap";
import VideoBanner from "@/Components/Home/VideoBanner";
import PhotoBannerSlider from "@/Components/Home/PhotoBanner/PhotoBannerSlider";
import BackToTopButton from "@/Components/Home/HomProductsSlider/BackToTopButton";
import Navbar from "@/Components/Navbar/Navbar";

export default function Home({products}) {
  console.log('products: ', products);

  return (
    <>
      <Head>
        <title>ShopKart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Slider products={products} />
        <HomeProductsHeading text={"Best Deals For You"} />
        <HomeProductSlider products={products} />
        <HomeProducts products={products} />
        <HomeProductsHeading text={"Discover"} />
        <Discover />
        <HomeProductsHeading text={"Explore More Items"} />
        <PhotoBannerSlider />
        <HomeProductsHeading text={"Dare to Leap"} />
        <DareToLeap />
        <VideoBanner />
        <BackToTopButton />
      </Box>
    </>
  );
}

export async function getStaticProps() {
  let res = await fetch("https://baby-blue-clam-wear.cyclic.app/products");
  let data = await res.json();

  return {
    props: {
      products: data,
    },
  };
}